#!/bin/bash

# prepare environment
module load miniforge3
source activate myenv_arbor

# set environment variables required to run custom Arbor installation
source set_arbor_env

# compile the mechanisms and build the catalogue
#rm -R -f ./tmp
#arbor-build-catalogue custom mechanisms --debug "./tmp"
arbor-build-catalogue custom mechanisms

conda deactivate
