#!/bin/bash

# set environment variables required to run custom Arbor installation
source set_arbor_env_gpu-use_gpu_rng

# compile the mechanisms and build the catalogue
arbor-build-catalogue custom mechanisms
