#!/usr/bin/bash

rm -R -f extract_10s-recall_ext_dendrites/data*
rm -R -f extract_10s-recall_small_dendrites/data*
rm -R -f extract_8h-recall_ext_dendrites/data*
rm -R -f extract_8h-recall_small_dendrites/data*

rm -R -f extract_10s-recall_ext_dendrites/Params*
rm -R -f extract_10s-recall_small_dendrites/Params*
rm -R -f extract_8h-recall_ext_dendrites/Params*
rm -R -f extract_8h-recall_small_dendrites/Params*

source data_show
