#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulations with standard parameters
python3 ./arborNetworkConsolidationMultiComp.py -s_desc="smallnet3 det, dt=0.2ms, 8h (ext. dendrites)" -dt=0.2 -runtime=28820 -learn='{"time_start": 10, "scheme": "TRIPLET", "freq": 100, "N_stim": 25}' -config_file="config_smallnet3_det_ext_dendrites.json" -sample_curr=0
