#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulations with standard parameters
python3 ./arborNetworkConsolidationMultiComp.py -runtime=28820 -learn='{"time_start": 10, "scheme": "TRIPLET", "freq": 100, "N_stim": 25}' -recall='{"time_start": 28810, "scheme": "ONEPULSE", "freq": 100, "N_stim": 25}' -s_desc="smallnet3 det, dt=0.2ms, 8h, with recall (small dendrites)" -dt=0.2 -config_file="config_smallnet3_det_small_dendrites.json" -sample_curr=0
