#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulations
python3.10 ./arborNetworkConsolidationMultiComp.py -config_file="config_smallnet2_basic_late_small_dendrites.json" -sample_curr=1
