#!/bin/bash

# build necessary catalogue (also sets the environment to run custom Arbor installation)
source build_catalogue

# run the simulations
python3.10 ./arborNetworkConsolidationMultiComp.py -config_file="config_smallnet2_basic_early.json" -output_period=1 -sample_curr=1
python3.10 ./arborNetworkConsolidationMultiComp.py -config_file="config_smallnet2_basic_early_det.json" -output_period=1 -sample_curr=1
