#!/bin/bash

num_trials=50

for (( i=1; i <= $num_trials; ++i ))
do
	# 10s-recall, large neurons with small dendrites
	sbatch run_defaultnet_10s-recall_large_cells_small_dendrites_gwdg-medium_cpu 100 $i
	sbatch run_defaultnet_10s-recall_large_cells_small_dendrites_gwdg-medium_cpu 150 $i
	sbatch run_defaultnet_10s-recall_large_cells_small_dendrites_gwdg-medium_cpu 200 $i
	sbatch run_defaultnet_10s-recall_large_cells_small_dendrites_gwdg-medium_cpu 250 $i

	# 10s-recall, large neurons with extended dendrites
	sbatch run_defaultnet_10s-recall_large_cells_ext_dendrites_gwdg-medium_cpu 100 $i
	sbatch run_defaultnet_10s-recall_large_cells_ext_dendrites_gwdg-medium_cpu 150 $i
	sbatch run_defaultnet_10s-recall_large_cells_ext_dendrites_gwdg-medium_cpu 200 $i
	sbatch run_defaultnet_10s-recall_large_cells_ext_dendrites_gwdg-medium_cpu 250 $i

	# 8h-recall, large neurons with small dendrites (formerly control)
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 100 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 150 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 200 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 250 1.0e-4 $i

	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 100 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 150 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 200 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 250 1.0e-8 $i

	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 100 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 150 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 200 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_small_dendrites_gwdg-medium_cpu 250 1.0e-12 $i

	# 8h-recall, large neurons with extended dendrites
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 100 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 150 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 200 1.0e-4 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 250 1.0e-4 $i

	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 100 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 150 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 200 1.0e-8 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 250 1.0e-8 $i

	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 100 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 150 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 200 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_large_cells_ext_dendrites_gwdg-medium_cpu 250 1.0e-12 $i
done
