#!/bin/bash

num_trials=1

for (( i=1; i <= $num_trials; ++i ))
do
	# 10s-recall, extended dendrites
	#sbatch run_defaultnet_10s-recall_ext_dendrites_gwdg-medium_cpu 100 $i

	# 8h-recall, small dendrites
	sbatch run_defaultnet_8h-recall_small_dendrites_gwdg-medium_cpu 100 1.0e-12 $i
	sbatch run_defaultnet_8h-recall_small_dendrites_gwdg-medium_cpu 200 1.0e-8 $i

	# 8h-recall, extended dendrites
	sbatch run_defaultnet_8h-recall_ext_dendrites_gwdg-medium_cpu 200 1.0e-4 $i
done
