#!/bin/bash

# Copyright 2023-2024 Jannik Luboeinski
# License: Apache-2.0 (http://www.apache.org/licenses/LICENSE-2.0)
# Contact: mail[at]jlubo.net

# create and enter directory for the output
if ! [[ -d 'pmap_output' ]]; then
	mkdir 'pmap_output'
fi

# wait for the process to start up
sleep 30s

# loop that prints the pmap information to a file every interval $2
while
	# find the process ID of the simulation process provided (name has to be provided as argument $1; the retrieved PID is the one of the oldest process whose
	# commandline argument starts with $1)
	regexp="^$1"
	echo "$regexp (oldest):"
	pid=$(pgrep -fo $regexp)
	echo "  $pid"

	# loop condition
	! [ "$pid" = "" ]
do
	# get and print the memory information ("Dirty" column returns dirty pages, both private and shared, in kilobytes; see https://linux.die.net/man/1/pmap)
	timestamp=`date +"%Y-%m-%d_%H-%M-%S"`
	sudo pmap -x ${pid} > pmap_output/pmap_output_${timestamp}_${pid}.log

	# set the sleep interval
	sleep $2
done

# gather the information in one file
ls -1 pmap_output/ > memory_usage_files.txt
grep -rh "total kB" pmap_output/*.log > memory_usage_data.txt
paste memory_usage_files.txt memory_usage_data.txt > memory_usage.txt
rm memory_usage_files.txt
rm memory_usage_data.txt
